"""
The product importer kept whatever text followed the description on the source
page, so 13 products carry a duplicated feature list plus stray storefront
chrome ("Read more USD base $80.00 USD Quantity - +") and raw HTML entities.
This trims each description back to its prose and writes the fixes as SQL.

Run:  python docs/clean-descriptions.py
Then: psql "$DATABASE_URL" -f docs/clean-descriptions.sql
"""
import html
import io
import json
import os
import re
import subprocess

API = "http://10.5.100.118:8080/api/products"
SQL_PATH = os.path.join("docs", "clean-descriptions.sql")


def clean(text: str) -> str:
    text = html.unescape(text or "")
    # Everything from the first bullet glyph on is the feature list, which the
    # product page already renders separately from products.features.
    text = re.split(r"[✦✧●•]", text)[0]
    # Trailing storefront chrome swept up by the scraper.
    text = re.sub(
        r"\s*(Read more|USD base|Quantity|Add to Bag|Buy now|In stock).*$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return re.sub(r"\s+", " ", text).strip()


def main() -> None:
    raw = json.loads(
        subprocess.run(["curl", "-s", API], capture_output=True, text=True,
                       encoding="utf-8", errors="ignore").stdout
    )
    products = raw if isinstance(raw, list) else raw.get("data") or []
    rows = []
    for p in products:
        before = p.get("description") or ""
        after = clean(before)
        if after and after != before:
            rows.append((p["slug"], after))
            print(f"  {p['slug']:52s} {len(before)} -> {len(after)}")

    lines = [
        "-- Generated by docs/clean-descriptions.py. Safe to re-run.",
        "BEGIN;",
        "",
    ]
    for slug, desc in rows:
        lines.append(
            "UPDATE products SET description = '{}' WHERE slug = '{}';".format(
                desc.replace("'", "''"), slug.replace("'", "''")
            )
        )
    lines += ["", "COMMIT;", ""]
    io.open(SQL_PATH, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"\nWrote {SQL_PATH} with {len(rows)} updates")


if __name__ == "__main__":
    main()
