"""
Backfill: products that reached us with a single image cannot do the catalog's
hover swap (cover packshot -> on-model shot), so their gallery is re-pulled
from auracojewelry.com, downloaded locally, and written back over
products.images. Only products where at least two images come back are
touched, so a failed scrape can never blank a product's artwork.

Run:  python docs/import-gallery-images.py
Then: psql "$DATABASE_URL" -f docs/gallery-images.sql
"""
import io
import json
import os
import re
import subprocess
import sys
import uuid

BASE = "https://auracojewelry.com"
OUT_IMG_DIR = os.path.join("public", "images", "products", "imported")
SQL_PATH = os.path.join("docs", "gallery-images.sql")
API = "http://10.5.100.118:8080/api/products"


def fetch(url: str) -> str:
    return subprocess.run(
        ["curl", "-sL", url], capture_output=True, text=True,
        encoding="utf-8", errors="ignore",
    ).stdout


def download(rel_url: str) -> str | None:
    name = f"{uuid.uuid4().hex}.webp"
    dest = os.path.join(OUT_IMG_DIR, name)
    r = subprocess.run(
        ["curl", "-sL", "-o", dest, "-w", "%{http_code}", BASE + rel_url],
        capture_output=True, text=True,
    )
    if r.stdout.strip() != "200" or not os.path.exists(dest) or os.path.getsize(dest) < 1000:
        if os.path.exists(dest):
            os.remove(dest)
        return None
    return "/images/products/imported/" + name


def gallery(slug: str) -> list[str]:
    html = fetch(f"{BASE}/product/{slug}")
    gal = re.search(r'<div class="pd-gallery"(.*?)<div class="product-detail__info"', html, re.S)
    seen, out = set(), []
    for u in re.findall(r"/storage/products/[^\"']+\.webp", gal.group(1) if gal else ""):
        if u not in seen:
            seen.add(u)
            out.append(u)
    return out[:5]


def main() -> None:
    os.makedirs(OUT_IMG_DIR, exist_ok=True)
    raw = json.loads(fetch(API))
    products = raw if isinstance(raw, list) else raw.get("data") or raw.get("products") or []
    targets = [p["slug"] for p in products if len(p.get("images") or []) < 2]
    print(f"{len(targets)} products need a gallery\n")

    rows = []
    for slug in targets:
        remote = gallery(slug)
        local = [d for d in (download(u) for u in remote) if d]
        status = "ok" if len(local) >= 2 else "SKIPPED"
        print(f"  {slug:52s} {len(local)} images  {status}")
        if len(local) >= 2:
            rows.append((slug, local))

    lines = [
        "-- Generated by docs/import-gallery-images.py. Safe to re-run.",
        "-- Only products whose gallery scraped cleanly are updated.",
        "BEGIN;",
        "",
    ]
    for slug, imgs in rows:
        payload = json.dumps(imgs).replace("'", "''")
        lines.append(
            f"UPDATE products SET images = '{payload}'::jsonb "
            f"WHERE slug = '{slug.replace(chr(39), chr(39) * 2)}';"
        )
    lines += ["", "COMMIT;", ""]
    io.open(SQL_PATH, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"\nWrote {SQL_PATH} with {len(rows)} updates")


if __name__ == "__main__":
    sys.exit(main())
