"""
One-off importer: pulls the nine Earrings products the clone was missing from
auracojewelry.com (the client's own live site), downloads their images into
public/images/products/imported/, and writes an idempotent SQL file that inserts them.

Run:  python docs/import-earrings.py
Then: psql -d auraco -f docs/earrings-import.sql   (on the container)

Not part of the app. Kept in the repo so the import can be re-run or audited.
"""
import io
import json
import os
import re
import subprocess
import uuid

BASE = "https://auracojewelry.com"
SLUGS = [
    "Astoria-Diamond-Cue-Solitaire-Earrings",
    "Aurelia-Fleur-Link-Earrings",
    "Ear-ssentials-Set",
    "Elara-Sculpted-Hoops",
    "Geometric-baguette-hoop-earrings",
    "Luminary-Triple-Stone-Crawler",
    "Madison-Pink-Sapphire-Dome-Huggies",
    "Montecito-Estate-Pearl-Earrings",
    "Sovereign-Dual-Tone-Huggies",
]
OUT_IMG_DIR = os.path.join("public", "images", "products", "imported")
SQL_PATH = os.path.join("docs", "earrings-import.sql")


def fetch(url: str) -> str:
    return subprocess.run(
        ["curl", "-sL", url], capture_output=True, text=True, encoding="utf-8"
    ).stdout


def strip_tags(s: str) -> str:
    s = re.sub(r"<[^>]+>", " ", s)
    s = (
        s.replace("&amp;", "&").replace("&quot;", '"').replace("&#039;", "'")
        .replace("&nbsp;", " ").replace("&lt;", "<").replace("&gt;", ">")
    )
    return re.sub(r"\s+", " ", s).strip()


def download(rel_url: str) -> str | None:
    """Download one image into OUT_IMG_DIR, return the public path we serve it at."""
    name = f"{uuid.uuid4().hex}.webp"
    dest = os.path.join(OUT_IMG_DIR, name)
    r = subprocess.run(
        ["curl", "-sL", "-o", dest, "-w", "%{http_code}", BASE + rel_url],
        capture_output=True, text=True,
    )
    if r.stdout.strip() != "200" or not os.path.exists(dest) or os.path.getsize(dest) < 1000:
        if os.path.exists(dest):
            os.remove(dest)
        return None
    return "/images/products/imported/" + name


def sql_str(v) -> str:
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def scrape(slug: str) -> dict:
    html = fetch(f"{BASE}/product/{slug}")

    if not html.strip():
        return {"slug": slug, "error": "empty response (404?)"}

    gal = re.search(r'<div class="pd-gallery"(.*?)<div class="product-detail__info"', html, re.S)
    imgs, seen = [], set()
    for u in re.findall(r"/storage/products/[^\"']+\.webp", gal.group(1) if gal else ""):
        if u not in seen:
            seen.add(u)
            imgs.append(u)

    info = re.search(r'<div class="product-detail__info"(.*?)</section>', html, re.S)
    info_txt = strip_tags(info.group(1)) if info else ""

    h1 = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.S)
    name = strip_tags(h1.group(1)) if h1 else slug.replace("-", " ")

    price_m = re.search(r"\$([\d,]+\.\d{2})", info_txt)
    price = float(price_m.group(1).replace(",", "")) if price_m else 0.0

    rat_m = re.search(r"([\d.]+)\s*\((\d+)\s+reviews?\)", info_txt)
    rating = float(rat_m.group(1)) if rat_m else 0.0
    reviews = int(rat_m.group(2)) if rat_m else 0

    feats = [strip_tags(li) for li in re.findall(r"<li[^>]*>(.*?)</li>", info.group(1) if info else "", re.S)]
    # Drop the trailing "<product name> $price" upsell row and anything oversized.
    feats = [f for f in feats if f and len(f) < 120 and "$" not in f][:6]

    material = next((f for f in feats if "Vermeil" in f or "Silver" in f or "Gold" in f), "18K Gold Vermeil")

    desc = ""
    wm = re.search(r"Why You'll Love It\s*:?(.*)", info_txt)
    if wm:
        desc = wm.group(1).strip()
        for stop in ("Free US Shipping", "Add to Bag", "Details", "Delivery"):
            i = desc.find(stop)
            if i > 80:
                desc = desc[:i].strip()
    desc = desc[:900]

    return {
        "slug": slug, "name": name, "price": price, "rating": rating,
        "reviews": reviews, "material": material, "features": feats,
        "description": desc, "remote_imgs": imgs[:5],
    }


def main() -> None:
    os.makedirs(OUT_IMG_DIR, exist_ok=True)
    rows = []
    failed = []
    for slug in SLUGS:
        p = scrape(slug)
        if p.get("error"):
            print(f"{slug:48s} FAILED: {p['error']}")
            failed.append(slug)
            continue
        local = [d for d in (download(u) for u in p["remote_imgs"]) if d]
        p["images"] = local
        if not p["price"] or not local:
            print(f"{p['name']:48s} ${p['price']:<8.2f} imgs={len(local)} feats={len(p['features'])}  ** WARNING: missing price or images **")
        else:
            print(f"{p['name']:48s} ${p['price']:<8.2f} imgs={len(local)} feats={len(p['features'])}")
        rows.append(p)

    lines = [
        "-- Generated by docs/import-earrings.py. Safe to re-run: ON CONFLICT DO NOTHING.",
        "BEGIN;",
        "",
    ]
    for p in rows:
        lines.append(
            "INSERT INTO products (slug, name, category, material, price, rating, "
            "review_count, images, description, features, stock, active) VALUES ("
            f"{sql_str(p['slug'])}, {sql_str(p['name'])}, 'Earrings', {sql_str(p['material'])}, "
            f"{p['price']}, {p['rating']}, {p['reviews']}, "
            f"{sql_str(json.dumps(p['images']))}::jsonb, {sql_str(p['description'])}, "
            f"{sql_str(json.dumps(p['features']))}::jsonb, 10, TRUE) "
            "ON CONFLICT (slug) DO NOTHING;"
        )
    lines += ["", "COMMIT;", ""]
    io.open(SQL_PATH, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"\nWrote {SQL_PATH}")
    if failed:
        print(f"FAILED slugs ({len(failed)}): {', '.join(failed)}")


if __name__ == "__main__":
    main()
